---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-model
  template:
    metadata:
      labels:
        app: game-model
    spec:
      containers:
      - name: application-container
        image: saikumar1817/mytetris:v1-2.0
        ports:
        - containerPort: 3000 
